name: Google Cloud Run Build & Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    - name: Build & Publish
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        docker build -t gcr.io/${PROJECT_ID}/${{xia.service-name}} .
        docker push gcr.io/${PROJECT_ID}/${{xia.service-name}}

    - name: User Creation
      continue-on-error: true
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        ${{xia.pub-create-topic}} --project ${PROJECT_ID}

    - name: Role Assign
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:${{xia.sa-name}}@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/logging.logWriter
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:${{xia.sa-name}}@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/run.invoker
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:${{xia.sa-name}}@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/${{xia.pub-role}}

    - name: Topic Creation
      continue-on-error: true
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        ${{xia.pub-create-topic}} --project ${PROJECT_ID}

    - name: Deploy
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud run deploy ${{xia.service-name}} --image gcr.io/${PROJECT_ID}/${{xia.service-name}} \
        --project ${PROJECT_ID} \
        --service-account ${{xia.sa-name}}@${PROJECT_ID}.iam.gserviceaccount.com \
        --region europe-west1 \
        --platform managed \
        --no-allow-unauthenticated \
        --update-env-vars XEED_USER=${{secrets.XEED_USER}},XEED_PASSWORD=${{secrets.XEED_PASSWORD}},XEED_DEST=$${PROJECT_ID},XEED_TOPIC=${{xia.topic}};
