name: Google Cloud Run Build & Deploy

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    - name: Build & Publish
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        docker build -t gcr.io/${PROJECT_ID}/xia-seeder-02 .
        docker push gcr.io/${PROJECT_ID}/xia-seeder-02

    - name: User Creation
      continue-on-error: true
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud iam service-accounts create gcr-xia-seeder-02 \
        --project ${PROJECT_ID} \
        --display-name "Cloud Run Xeed Http Endpoint"

    - name: Role Assign
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:gcr-xia-seeder-02@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/logging.logWriter
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:gcr-xia-seeder-02@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/run.invoker
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member=serviceAccount:gcr-xia-seeder-02@${PROJECT_ID}.iam.gserviceaccount.com \
        --role=roles/run.invoker

    - name: Topic Creation
      continue-on-error: true
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud pubsub topics create test-002 --project ${PROJECT_ID}

    - name: Deploy
      run: |
        PROJECT_ID=$(gcloud config list --format 'value(core.account)' | sed 's/.*@\(.*\)\.iam\.gserviceaccount.*/\1/')
        gcloud run deploy xia-seeder-02 --image gcr.io/${PROJECT_ID}/xia-seeder-02 \
        --project ${PROJECT_ID} \
        --service-account gcr-xia-seeder-02@${PROJECT_ID}.iam.gserviceaccount.com \
        --region europe-west1 \
        --platform managed \
        --allow-unauthenticated \
        --update-env-vars XEED_USER=${{secrets.XEED_USER}},XEED_PASSWORD=${{secrets.XEED_PASSWORD}},XEED_DEST=xia-dispatcher-zmfr66omva-ew.a.run.app,XEED_TOPIC=test-002,XEED_INSIGHT=xia-receiver-zmfr66omva-ew.a.run.app;
